name: Get Found
favicon: null
layout_spectrum: 0.65523
typography_spectrum: 0.56398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#021325'
    - '#989699'
    - '#28425b'
    - '#677c8d'
    - '#e8c097'
  brandStrength: 0.9171832
  lightness: 0.3001574
  saturation: 0.538358
  rhythmicContrast: 0.4076177
purpose: []
