layout_spectrum: 0.5286738
color:
  saturation: 0.538358
  lightness: 0.3001574
  brandStrength: 0.9171832
  brandColors:
    - '#65A4B5'
    - '#FFFFFF'
    - '#145270'
    - '#421417'
    - '#77656E'
  rhythmicContrast: 0.4076177
typography_spectrum: 1
name: Get Found
